<?xml version="1.0" encoding="utf-8"?>
<Database Name="MvcForum" EntityNamespace="MvcForum" Class="MvcForumDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=MvcForum;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MvcForumConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Answers" Member="Answers">
    <Type Name="Answer">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="AuthorId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Answer_Question" Member="Questions" ThisKey="Id" OtherKey="CorrectAnswerId" Type="Question" />
      <Association Name="User_Answer" Member="User" ThisKey="AuthorId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Question_Answer" Member="Question" ThisKey="QuestionId" OtherKey="Id" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Answer" Member="Answers" ThisKey="Id" OtherKey="AuthorId" Type="Answer" />
      <Association Name="User_Question" Member="Questions" ThisKey="Id" OtherKey="AuthorId" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Question">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="AuthorId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CorrectAnswerId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Question_Answer" Member="Answers" ThisKey="Id" OtherKey="QuestionId" Type="Answer" />
      <Association Name="Answer_Question" Member="Answer" ThisKey="CorrectAnswerId" OtherKey="Id" Type="Answer" IsForeignKey="true" />
      <Association Name="User_Question" Member="User" ThisKey="AuthorId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>